name: AlipaySignIn

on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '0 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run
      run: python alipay.py
      env:
        URL: ${{secrets.URL}}
        COOKIES: ${{secrets.COOKIES}}
        SIGNDATA: ${{secrets.SIGNDATA}}
        FORMDATA: ${{secrets.FORMDATA}}

    - name: Run Another
      run: python wechat.py
      env:
        USERNAME: ${{secrets.USERNAME}}
        PASSWORD: ${{secrets.PASSWORD}}
        WECHAT_DATA: ${{secrets.WECHAT_DATA}}

    - name: Send Notification
      uses: Zxilly/action-notify@v0.0.2
      with:
        user_id: zxilly
        content: 每日打卡完成
        title: 疫情打卡
