name: AlipaySignIn

on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '0 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run
      run: python main.py
      env:
        URL: ${{secrets.URL}}
        COOKIES: ${{secrets.COOKIES}}
        SIGNDATA: ${{secrets.SIGNDATA}}
        FORMDATA: ${{secrets.FORMDATA}}
    - name: Send Notification
  # You may pin to the exact commit or the version.
  # uses: Zxilly/action-notify@f998cf5ea223975e4de9ceef7e6f980ec9da6844
      uses: Zxilly/action-notify@v0.0.2
      with:
    # The user will be notified.
        user_id: zxilly
    # Notification content.
        content: 每日打卡完成
    # Notification title.
        title: 支付宝打卡
